#!/usr/bin/env bash
# gitea-skills installer.
#
# Stores GITEA_HOST + GITEA_ACCESS_TOKEN in ~/.config/gitea-skills/config
# (chmod 600, directory 700). All gitea-* skills source this file
# automatically before making API calls.
#
# Usage:
#   ./setup.sh              interactive setup
#   ./setup.sh --uninstall  remove the config file
#   ./setup.sh --print      show where the config lives
#   ./setup.sh --help       show this help
#
# Existing env vars (e.g. from direnv) take precedence; values written here
# are used as fallbacks when those env vars are not set.

set -euo pipefail

CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/gitea-skills"
CFG_FILE="$CFG_DIR/config"

red()    { printf '\033[31m%s\033[0m\n' "$*" >&2; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

usage() {
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

prompt() {
  local label="$1" var="$2" default="${3:-}" hidden="${4:-no}"
  local val=""
  if [ "$hidden" = "yes" ]; then
    printf '%s: ' "$label" >&2
    if command -v stty >/dev/null 2>&1; then
      stty -echo
    fi
    IFS= read -r val
    if command -v stty >/dev/null 2>&1; then
      stty echo
    fi
    printf '\n' >&2
  else
    if [ -n "$default" ]; then
      printf '%s [%s]: ' "$label" "$default" >&2
    else
      printf '%s: ' "$label" >&2
    fi
    IFS= read -r val
    [ -z "$val" ] && val="$default"
  fi
  eval "$var=\$val"
}

confirm() {
  local label="$1"
  printf '%s [y/N]: ' "$label" >&2
  local ans
  IFS= read -r ans
  case "${ans:-}" in y|Y|yes|Yes) return 0 ;; *) return 1 ;; esac
}

cmd_uninstall() {
  if [ ! -e "$CFG_FILE" ]; then
    yellow "No config at $CFG_FILE — nothing to do."
    return 0
  fi
  yellow "Will remove $CFG_FILE"
  if confirm "Continue?"; then
    rm -f "$CFG_FILE"
    green "Removed."
    # If directory is empty, clean it up too.
    rmdir "$CFG_DIR" 2>/dev/null || true
  else
    echo "Aborted."
  fi
}

cmd_print() {
  if [ -f "$CFG_FILE" ]; then
    echo "$CFG_FILE"
  else
    yellow "(no config installed)"
    echo "Would install to: $CFG_FILE"
    exit 1
  fi
}

cmd_install() {
  bold "============================================================"
  bold " gitea-skills installer"
  bold "============================================================"
  echo
  echo "This stores your Gitea host + access token in:"
  echo "  $CFG_FILE  (chmod 600)"
  echo
  echo "Every gitea-* skill auto-sources this file before making API"
  echo "calls. Existing GITEA_HOST / GITEA_ACCESS_TOKEN env vars (from"
  echo "direnv, your shell rc, etc.) take precedence over this file."
  echo

  if [ -f "$CFG_FILE" ]; then
    yellow "Existing config found."
    if ! confirm "Overwrite?"; then
      echo "Aborted. Existing config kept."
      exit 0
    fi
  fi

  # Default the host prompt from existing env if any.
  DEFAULT_HOST="${GITEA_HOST:-}"
  prompt "Gitea host (e.g. https://gitea.example.com)" HOST "$DEFAULT_HOST"

  if [ -z "${HOST:-}" ]; then
    red "host is required"
    exit 1
  fi
  HOST="${HOST%/}"   # strip trailing slash

  prompt "Personal access token (input hidden)" TOKEN "" yes
  if [ -z "${TOKEN:-}" ]; then
    red "token is required"
    exit 1
  fi

  # Validate
  echo
  echo "Validating..."
  local VER LOGIN ok=1
  if VER=$(curl -fsSL --max-time 10 "$HOST/api/v1/version" 2>/dev/null \
           | jq -r .version 2>/dev/null) && [ -n "$VER" ] && [ "$VER" != "null" ]; then
    green "  /version          ok ($VER)"
  else
    red   "  /version          unreachable at $HOST"
    ok=0
  fi

  if LOGIN=$(curl -fsSL --max-time 10 \
              -H "Authorization: token $TOKEN" \
              "$HOST/api/v1/user" 2>/dev/null \
              | jq -r .login 2>/dev/null) && [ -n "$LOGIN" ] && [ "$LOGIN" != "null" ]; then
    green "  /user             ok (authenticated as $LOGIN)"
  else
    red   "  /user             auth failed (token invalid?)"
    ok=0
  fi

  if [ "$ok" -ne 1 ]; then
    echo
    yellow "Validation did not fully pass."
    if ! confirm "Save config anyway?"; then
      exit 1
    fi
  fi

  # Write
  mkdir -p "$CFG_DIR"
  chmod 700 "$CFG_DIR"

  local now
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  umask 077
  cat > "$CFG_FILE" <<EOF
# gitea-skills config
# Generated by setup.sh on $now
# Sourced by gitea-* skills. Do not commit this file.
#
# Existing env vars take precedence; lines below set defaults only when
# the variable is not already exported.

: "\${GITEA_HOST:=$HOST}"
: "\${GITEA_ACCESS_TOKEN:=$TOKEN}"
export GITEA_HOST GITEA_ACCESS_TOKEN
EOF
  chmod 600 "$CFG_FILE"

  echo
  green "Wrote $CFG_FILE"
  echo
  echo "Next:"
  echo "  - Skills will auto-source this file. No further action."
  echo "  - Rotate token:  ./setup.sh"
  echo "  - Remove:        ./setup.sh --uninstall"
}

# ---- entry ----
case "${1:-}" in
  -h|--help)       usage 0 ;;
  --uninstall)     cmd_uninstall ;;
  --print)         cmd_print ;;
  "")              cmd_install ;;
  *)               red "Unknown arg: $1"; usage 1 ;;
esac
